import lfaf.university.labs2026.RegexGenerator;
import org.junit.Test;

import java.util.Set;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertEquals;

public class RegexGeneratorTest {
    private static void assertSetsMatch(Set<String> expected, Set<String> actual) {
        assertEquals("Set sizes differ", expected.size(), actual.size());
        assertTrue("Actual set is missing expected elements", actual.containsAll(expected));
        assertTrue("Expected set contains elements not present in actual", expected.containsAll(actual));
    }

    @Test
    public void firstExample(){
        var generator = new RegexGenerator();
        var actual = generator.generate("M?N{2}(O|P){3}Q*R+");
        var expected = Set.of(
                "NNOOOR", "NNOOORR", "NNOOORRR", "NNOOORRRR", "NNOOORRRRR",
                "NNOOOQR", "NNOOOQRR", "NNOOOQRRR", "NNOOOQRRRR", "NNOOOQRRRRR",
                "NNOOOQQR", "NNOOOQQRR", "NNOOOQQRRR", "NNOOOQQRRRR", "NNOOOQQRRRRR",
                "NNOOOQQQR", "NNOOOQQQRR", "NNOOOQQQRRR", "NNOOOQQQRRRR", "NNOOOQQQRRRRR",
                "NNOOOQQQQR", "NNOOOQQQQRR", "NNOOOQQQQRRR", "NNOOOQQQQRRRR", "NNOOOQQQQRRRRR",
                "NNOOOQQQQQR", "NNOOOQQQQQRR", "NNOOOQQQQQRRR", "NNOOOQQQQQRRRR", "NNOOOQQQQQRRRRR",

                "NNOOPR", "NNOOPRR", "NNOOPRRR", "NNOOPRRRR", "NNOOPRRRRR",
                "NNOOPQR", "NNOOPQRR", "NNOOPQRRR", "NNOOPQRRRR", "NNOOPQRRRRR",
                "NNOOPQQR", "NNOOPQQRR", "NNOOPQQRRR", "NNOOPQQRRRR", "NNOOPQQRRRRR",
                "NNOOPQQQR", "NNOOPQQQRR", "NNOOPQQQRRR", "NNOOPQQQRRRR", "NNOOPQQQRRRRR",
                "NNOOPQQQQR", "NNOOPQQQQRR", "NNOOPQQQQRRR", "NNOOPQQQQRRRR", "NNOOPQQQQRRRRR",
                "NNOOPQQQQQR", "NNOOPQQQQQRR", "NNOOPQQQQQRRR", "NNOOPQQQQQRRRR", "NNOOPQQQQQRRRRR",

                "NNOPOR", "NNOPORR", "NNOPORRR", "NNOPORRRR", "NNOPORRRRR",
                "NNOPOQR", "NNOPOQRR", "NNOPOQRRR", "NNOPOQRRRR", "NNOPOQRRRRR",
                "NNOPOQQR", "NNOPOQQRR", "NNOPOQQRRR", "NNOPOQQRRRR", "NNOPOQQRRRRR",
                "NNOPOQQQR", "NNOPOQQQRR", "NNOPOQQQRRR", "NNOPOQQQRRRR", "NNOPOQQQRRRRR",
                "NNOPOQQQQR", "NNOPOQQQQRR", "NNOPOQQQQRRR", "NNOPOQQQQRRRR", "NNOPOQQQQRRRRR",
                "NNOPOQQQQQR", "NNOPOQQQQQRR", "NNOPOQQQQQRRR", "NNOPOQQQQQRRRR", "NNOPOQQQQQRRRRR",

                "NNOPPR", "NNOPPRR", "NNOPPRRR", "NNOPPRRRR", "NNOPPRRRRR",
                "NNOPPQR", "NNOPPQRR", "NNOPPQRRR", "NNOPPQRRRR", "NNOPPQRRRRR",
                "NNOPPQQR", "NNOPPQQRR", "NNOPPQQRRR", "NNOPPQQRRRR", "NNOPPQQRRRRR",
                "NNOPPQQQR", "NNOPPQQQRR", "NNOPPQQQRRR", "NNOPPQQQRRRR", "NNOPPQQQRRRRR",
                "NNOPPQQQQR", "NNOPPQQQQRR", "NNOPPQQQQRRR", "NNOPPQQQQRRRR", "NNOPPQQQQRRRRR",
                "NNOPPQQQQQR", "NNOPPQQQQQRR", "NNOPPQQQQQRRR", "NNOPPQQQQQRRRR", "NNOPPQQQQQRRRRR",

                "NNPOOR", "NNPOORR", "NNPOORRR", "NNPOORRRR", "NNPOORRRRR",
                "NNPOOQR", "NNPOOQRR", "NNPOOQRRR", "NNPOOQRRRR", "NNPOOQRRRRR",
                "NNPOOQQR", "NNPOOQQRR", "NNPOOQQRRR", "NNPOOQQRRRR", "NNPOOQQRRRRR",
                "NNPOOQQQR", "NNPOOQQQRR", "NNPOOQQQRRR", "NNPOOQQQRRRR", "NNPOOQQQRRRRR",
                "NNPOOQQQQR", "NNPOOQQQQRR", "NNPOOQQQQRRR", "NNPOOQQQQRRRR", "NNPOOQQQQRRRRR",
                "NNPOOQQQQQR", "NNPOOQQQQQRR", "NNPOOQQQQQRRR", "NNPOOQQQQQRRRR", "NNPOOQQQQQRRRRR",

                "NNPOPR", "NNPOPRR", "NNPOPRRR", "NNPOPRRRR", "NNPOPRRRRR",
                "NNPOPQR", "NNPOPQRR", "NNPOPQRRR", "NNPOPQRRRR", "NNPOPQRRRRR",
                "NNPOPQQR", "NNPOPQQRR", "NNPOPQQRRR", "NNPOPQQRRRR", "NNPOPQQRRRRR",
                "NNPOPQQQR", "NNPOPQQQRR", "NNPOPQQQRRR", "NNPOPQQQRRRR", "NNPOPQQQRRRRR",
                "NNPOPQQQQR", "NNPOPQQQQRR", "NNPOPQQQQRRR", "NNPOPQQQQRRRR", "NNPOPQQQQRRRRR",
                "NNPOPQQQQQR", "NNPOPQQQQQRR", "NNPOPQQQQQRRR", "NNPOPQQQQQRRRR", "NNPOPQQQQQRRRRR",

                "NNPPOR", "NNPPORR", "NNPPORRR", "NNPPORRRR", "NNPPORRRRR",
                "NNPPOQR", "NNPPOQRR", "NNPPOQRRR", "NNPPOQRRRR", "NNPPOQRRRRR",
                "NNPPOQQR", "NNPPOQQRR", "NNPPOQQRRR", "NNPPOQQRRRR", "NNPPOQQRRRRR",
                "NNPPOQQQR", "NNPPOQQQRR", "NNPPOQQQRRR", "NNPPOQQQRRRR", "NNPPOQQQRRRRR",
                "NNPPOQQQQR", "NNPPOQQQQRR", "NNPPOQQQQRRR", "NNPPOQQQQRRRR", "NNPPOQQQQRRRRR",
                "NNPPOQQQQQR", "NNPPOQQQQQRR", "NNPPOQQQQQRRR", "NNPPOQQQQQRRRR", "NNPPOQQQQQRRRRR",

                "NNPPPR", "NNPPPRR", "NNPPPRRR", "NNPPPRRRR", "NNPPPRRRRR",
                "NNPPPQR", "NNPPPQRR", "NNPPPQRRR", "NNPPPQRRRR", "NNPPPQRRRRR",
                "NNPPPQQR", "NNPPPQQRR", "NNPPPQQRRR", "NNPPPQQRRRR", "NNPPPQQRRRRR",
                "NNPPPQQQR", "NNPPPQQQRR", "NNPPPQQQRRR", "NNPPPQQQRRRR", "NNPPPQQQRRRRR",
                "NNPPPQQQQR", "NNPPPQQQQRR", "NNPPPQQQQRRR", "NNPPPQQQQRRRR", "NNPPPQQQQRRRRR",
                "NNPPPQQQQQR", "NNPPPQQQQQRR", "NNPPPQQQQQRRR", "NNPPPQQQQQRRRR", "NNPPPQQQQQRRRRR",
                "MNNOOOR", "MNNOOORR", "MNNOOORRR", "MNNOOORRRR", "MNNOOORRRRR",
                "MNNOOOQR", "MNNOOOQRR", "MNNOOOQRRR", "MNNOOOQRRRR", "MNNOOOQRRRRR",
                "MNNOOOQQR", "MNNOOOQQRR", "MNNOOOQQRRR", "MNNOOOQQRRRR", "MNNOOOQQRRRRR",
                "MNNOOOQQQR", "MNNOOOQQQRR", "MNNOOOQQQRRR", "MNNOOOQQQRRRR", "MNNOOOQQQRRRRR",
                "MNNOOOQQQQR", "MNNOOOQQQQRR", "MNNOOOQQQQRRR", "MNNOOOQQQQRRRR", "MNNOOOQQQQRRRRR",
                "MNNOOOQQQQQR", "MNNOOOQQQQQRR", "MNNOOOQQQQQRRR", "MNNOOOQQQQQRRRR", "MNNOOOQQQQQRRRRR",

                "MNNOOPR", "MNNOOPRR", "MNNOOPRRR", "MNNOOPRRRR", "MNNOOPRRRRR",
                "MNNOOPQR", "MNNOOPQRR", "MNNOOPQRRR", "MNNOOPQRRRR", "MNNOOPQRRRRR",
                "MNNOOPQQR", "MNNOOPQQRR", "MNNOOPQQRRR", "MNNOOPQQRRRR", "MNNOOPQQRRRRR",
                "MNNOOPQQQR", "MNNOOPQQQRR", "MNNOOPQQQRRR", "MNNOOPQQQRRRR", "MNNOOPQQQRRRRR",
                "MNNOOPQQQQR", "MNNOOPQQQQRR", "MNNOOPQQQQRRR", "MNNOOPQQQQRRRR", "MNNOOPQQQQRRRRR",
                "MNNOOPQQQQQR", "MNNOOPQQQQQRR", "MNNOOPQQQQQRRR", "MNNOOPQQQQQRRRR", "MNNOOPQQQQQRRRRR",

                "MNNOPOR", "MNNOPORR", "MNNOPORRR", "MNNOPORRRR", "MNNOPORRRRR",
                "MNNOPOQR", "MNNOPOQRR", "MNNOPOQRRR", "MNNOPOQRRRR", "MNNOPOQRRRRR",
                "MNNOPOQQR", "MNNOPOQQRR", "MNNOPOQQRRR", "MNNOPOQQRRRR", "MNNOPOQQRRRRR",
                "MNNOPOQQQR", "MNNOPOQQQRR", "MNNOPOQQQRRR", "MNNOPOQQQRRRR", "MNNOPOQQQRRRRR",
                "MNNOPOQQQQR", "MNNOPOQQQQRR", "MNNOPOQQQQRRR", "MNNOPOQQQQRRRR", "MNNOPOQQQQRRRRR",
                "MNNOPOQQQQQR", "MNNOPOQQQQQRR", "MNNOPOQQQQQRRR", "MNNOPOQQQQQRRRR", "MNNOPOQQQQQRRRRR",

                "MNNOPPR", "MNNOPPRR", "MNNOPPRRR", "MNNOPPRRRR", "MNNOPPRRRRR",
                "MNNOPPQR", "MNNOPPQRR", "MNNOPPQRRR", "MNNOPPQRRRR", "MNNOPPQRRRRR",
                "MNNOPPQQR", "MNNOPPQQRR", "MNNOPPQQRRR", "MNNOPPQQRRRR", "MNNOPPQQRRRRR",
                "MNNOPPQQQR", "MNNOPPQQQRR", "MNNOPPQQQRRR", "MNNOPPQQQRRRR", "MNNOPPQQQRRRRR",
                "MNNOPPQQQQR", "MNNOPPQQQQRR", "MNNOPPQQQQRRR", "MNNOPPQQQQRRRR", "MNNOPPQQQQRRRRR",
                "MNNOPPQQQQQR", "MNNOPPQQQQQRR", "MNNOPPQQQQQRRR", "MNNOPPQQQQQRRRR", "MNNOPPQQQQQRRRRR",

                "MNNPOOR", "MNNPOORR", "MNNPOORRR", "MNNPOORRRR", "MNNPOORRRRR",
                "MNNPOOQR", "MNNPOOQRR", "MNNPOOQRRR", "MNNPOOQRRRR", "MNNPOOQRRRRR",
                "MNNPOOQQR", "MNNPOOQQRR", "MNNPOOQQRRR", "MNNPOOQQRRRR", "MNNPOOQQRRRRR",
                "MNNPOOQQQR", "MNNPOOQQQRR", "MNNPOOQQQRRR", "MNNPOOQQQRRRR", "MNNPOOQQQRRRRR",
                "MNNPOOQQQQR", "MNNPOOQQQQRR", "MNNPOOQQQQRRR", "MNNPOOQQQQRRRR", "MNNPOOQQQQRRRRR",
                "MNNPOOQQQQQR", "MNNPOOQQQQQRR", "MNNPOOQQQQQRRR", "MNNPOOQQQQQRRRR", "MNNPOOQQQQQRRRRR",

                "MNNPOPR", "MNNPOPRR", "MNNPOPRRR", "MNNPOPRRRR", "MNNPOPRRRRR",
                "MNNPOPQR", "MNNPOPQRR", "MNNPOPQRRR", "MNNPOPQRRRR", "MNNPOPQRRRRR",
                "MNNPOPQQR", "MNNPOPQQRR", "MNNPOPQQRRR", "MNNPOPQQRRRR", "MNNPOPQQRRRRR",
                "MNNPOPQQQR", "MNNPOPQQQRR", "MNNPOPQQQRRR", "MNNPOPQQQRRRR", "MNNPOPQQQRRRRR",
                "MNNPOPQQQQR", "MNNPOPQQQQRR", "MNNPOPQQQQRRR", "MNNPOPQQQQRRRR", "MNNPOPQQQQRRRRR",
                "MNNPOPQQQQQR", "MNNPOPQQQQQRR", "MNNPOPQQQQQRRR", "MNNPOPQQQQQRRRR", "MNNPOPQQQQQRRRRR",

                "MNNPPOR", "MNNPPORR", "MNNPPORRR", "MNNPPORRRR", "MNNPPORRRRR",
                "MNNPPOQR", "MNNPPOQRR", "MNNPPOQRRR", "MNNPPOQRRRR", "MNNPPOQRRRRR",
                "MNNPPOQQR", "MNNPPOQQRR", "MNNPPOQQRRR", "MNNPPOQQRRRR", "MNNPPOQQRRRRR",
                "MNNPPOQQQR", "MNNPPOQQQRR", "MNNPPOQQQRRR", "MNNPPOQQQRRRR", "MNNPPOQQQRRRRR",
                "MNNPPOQQQQR", "MNNPPOQQQQRR", "MNNPPOQQQQRRR", "MNNPPOQQQQRRRR", "MNNPPOQQQQRRRRR",
                "MNNPPOQQQQQR", "MNNPPOQQQQQRR", "MNNPPOQQQQQRRR", "MNNPPOQQQQQRRRR", "MNNPPOQQQQQRRRRR",

                "MNNPPPR", "MNNPPPRR", "MNNPPPRRR", "MNNPPPRRRR", "MNNPPPRRRRR",
                "MNNPPPQR", "MNNPPPQRR", "MNNPPPQRRR", "MNNPPPQRRRR", "MNNPPPQRRRRR",
                "MNNPPPQQR", "MNNPPPQQRR", "MNNPPPQQRRR", "MNNPPPQQRRRR", "MNNPPPQQRRRRR",
                "MNNPPPQQQR", "MNNPPPQQQRR", "MNNPPPQQQRRR", "MNNPPPQQQRRRR", "MNNPPPQQQRRRRR",
                "MNNPPPQQQQR", "MNNPPPQQQQRR", "MNNPPPQQQQRRR", "MNNPPPQQQQRRRR", "MNNPPPQQQQRRRRR",
                "MNNPPPQQQQQR", "MNNPPPQQQQQRR", "MNNPPPQQQQQRRR", "MNNPPPQQQQQRRRR", "MNNPPPQQQQQRRRRR");

        assertSetsMatch(expected, actual);
    }

    @Test
    public void secondExample(){
        var generator = new RegexGenerator();
        var actual = generator.generate("(X|Y|Z){3}8+(9|0)");
        var expected = Set.of(
                "XXX89", "XXX80", "XXX889", "XXX880", "XXX8889", "XXX8880", "XXX88889", "XXX88880", "XXX888889", "XXX888880",
                "XXY89", "XXY80", "XXY889", "XXY880", "XXY8889", "XXY8880", "XXY88889", "XXY88880", "XXY888889", "XXY888880",
                "XXZ89", "XXZ80", "XXZ889", "XXZ880", "XXZ8889", "XXZ8880", "XXZ88889", "XXZ88880", "XXZ888889", "XXZ888880",
                "XYX89", "XYX80", "XYX889", "XYX880", "XYX8889", "XYX8880", "XYX88889", "XYX88880", "XYX888889", "XYX888880",
                "XYY89", "XYY80", "XYY889", "XYY880", "XYY8889", "XYY8880", "XYY88889", "XYY88880", "XYY888889", "XYY888880",
                "XYZ89", "XYZ80", "XYZ889", "XYZ880", "XYZ8889", "XYZ8880", "XYZ88889", "XYZ88880", "XYZ888889", "XYZ888880",
                "XZX89", "XZX80", "XZX889", "XZX880", "XZX8889", "XZX8880", "XZX88889", "XZX88880", "XZX888889", "XZX888880",
                "XZY89", "XZY80", "XZY889", "XZY880", "XZY8889", "XZY8880", "XZY88889", "XZY88880", "XZY888889", "XZY888880",
                "XZZ89", "XZZ80", "XZZ889", "XZZ880", "XZZ8889", "XZZ8880", "XZZ88889", "XZZ88880", "XZZ888889", "XZZ888880",
                "YXX89", "YXX80", "YXX889", "YXX880", "YXX8889", "YXX8880", "YXX88889", "YXX88880", "YXX888889", "YXX888880",
                "YXY89", "YXY80", "YXY889", "YXY880", "YXY8889", "YXY8880", "YXY88889", "YXY88880", "YXY888889", "YXY888880",
                "YXZ89", "YXZ80", "YXZ889", "YXZ880", "YXZ8889", "YXZ8880", "YXZ88889", "YXZ88880", "YXZ888889", "YXZ888880",
                "YYX89", "YYX80", "YYX889", "YYX880", "YYX8889", "YYX8880", "YYX88889", "YYX88880", "YYX888889", "YYX888880",
                "YYY89", "YYY80", "YYY889", "YYY880", "YYY8889", "YYY8880", "YYY88889", "YYY88880", "YYY888889", "YYY888880",
                "YYZ89", "YYZ80", "YYZ889", "YYZ880", "YYZ8889", "YYZ8880", "YYZ88889", "YYZ88880", "YYZ888889", "YYZ888880",
                "YZX89", "YZX80", "YZX889", "YZX880", "YZX8889", "YZX8880", "YZX88889", "YZX88880", "YZX888889", "YZX888880",
                "YZY89", "YZY80", "YZY889", "YZY880", "YZY8889", "YZY8880", "YZY88889", "YZY88880", "YZY888889", "YZY888880",
                "YZZ89", "YZZ80", "YZZ889", "YZZ880", "YZZ8889", "YZZ8880", "YZZ88889", "YZZ88880", "YZZ888889", "YZZ888880",
                "ZXX89", "ZXX80", "ZXX889", "ZXX880", "ZXX8889", "ZXX8880", "ZXX88889", "ZXX88880", "ZXX888889", "ZXX888880",
                "ZXY89", "ZXY80", "ZXY889", "ZXY880", "ZXY8889", "ZXY8880", "ZXY88889", "ZXY88880", "ZXY888889", "ZXY888880",
                "ZXZ89", "ZXZ80", "ZXZ889", "ZXZ880", "ZXZ8889", "ZXZ8880", "ZXZ88889", "ZXZ88880", "ZXZ888889", "ZXZ888880",
                "ZYX89", "ZYX80", "ZYX889", "ZYX880", "ZYX8889", "ZYX8880", "ZYX88889", "ZYX88880", "ZYX888889", "ZYX888880",
                "ZYY89", "ZYY80", "ZYY889", "ZYY880", "ZYY8889", "ZYY8880", "ZYY88889", "ZYY88880", "ZYY888889", "ZYY888880",
                "ZYZ89", "ZYZ80", "ZYZ889", "ZYZ880", "ZYZ8889", "ZYZ8880", "ZYZ88889", "ZYZ88880", "ZYZ888889", "ZYZ888880",
                "ZZX89", "ZZX80", "ZZX889", "ZZX880", "ZZX8889", "ZZX8880", "ZZX88889", "ZZX88880", "ZZX888889", "ZZX888880",
                "ZZY89", "ZZY80", "ZZY889", "ZZY880", "ZZY8889", "ZZY8880", "ZZY88889", "ZZY88880", "ZZY888889", "ZZY888880",
                "ZZZ89", "ZZZ80", "ZZZ889", "ZZZ880", "ZZZ8889", "ZZZ8880", "ZZZ88889", "ZZZ88880", "ZZZ888889", "ZZZ888880");

        assertSetsMatch(expected, actual);
    }

    @Test
    public void thirdExample(){
        var generator = new RegexGenerator();
        var actual = generator.generate("(H|i)(J|K)L*N?");
        var expected = Set.of(
                "HJN", "HJLN", "HJLLN", "HJLLLN", "HJLLLLN", "HJLLLLLN",
                "HJ", "HJL", "HJLL", "HJLLL", "HJLLLL", "HJLLLLL",
                "HKN", "HKLN", "HKLLN", "HKLLLN", "HKLLLLN", "HKLLLLLN",
                "HK", "HKL", "HKLL", "HKLLL", "HKLLLL", "HKLLLLL",
                "iJN", "iJLN", "iJLLN", "iJLLLN", "iJLLLLN", "iJLLLLLN",
                "iJ", "iJL", "iJLL", "iJLLL", "iJLLLL", "iJLLLLL",
                "iKN", "iKLN", "iKLLN", "iKLLLN", "iKLLLLN", "iKLLLLLN",
                "iK", "iKL", "iKLL", "iKLLL", "iKLLLL", "iKLLLLL");

        assertSetsMatch(expected, actual);
    }
}
